version: '3.9'
services:
  admin:
    build: ./admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./admin:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

 
  main:
    build: ./main
    command: python main.py  
    volumes:
      - ./main:/app
    ports:
      - "8001:5000"
    depends_on:
      - db_main

  
  db_main:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: main_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./main/.dbdata:/var/lib/mysql 
    ports:
      - 33067:3306
  
  queue:
    image: rabbitmq:3-management
    container_name: queue
    ports:
      - 5672:5672
      - 15672:15672